In [1]:
#importing necssary files
from __future__ import division, print_function, unicode_literals
import numpy as np
import pandas as pd 
get_ipython().magic(u'matplotlib inline')
import matplotlib
import math as mt
import matplotlib.pyplot as plt
from matplotlib.mlab import PCA

#printing versions of current packages in use 
print(np.__version__)
print(pd.__version__)
print(matplotlib.__version__)

#importing the csv file containing data of sensors, sorting them and selecting the required columns
DataFile = pd.read_csv('C:/Users/muneeba/Desktop/THESIS/DataDistributionPCA.csv')
location=DataFile.iloc[:,1:3]
DataSensors=DataFile.iloc[:,4:68]

#converting the sliced data into matrices 
returns = DataSensors[[key for key in dict(DataSensors.dtypes) if dict(DataSensors.dtypes)[key] in ['float64', 'int64']]] 
returns = returns[:65]
returns_arr = returns.as_matrix()[:65]
locations = location[[key for key in dict(location.dtypes) if dict(location.dtypes)[key] in ['float64', 'int64']]] 
locations = locations[:65] 
locations_arr = locations.as_matrix()[:65]

1.12.1
0.22.0
2.2.0


In [16]:
errorvalues=[-1.489132543146572951e-01,-1.238246082072965715e-01,-4.054648935415397504e-02,-5.268615682545755088e-03,-4.524049410972469528e-04
,-4.839680765226362486e-04,
-5.317174352430971158e-04,
-2.541237057326217351e-04,
-2.063743470121609525e-01,
-2.063743470121609525e-01,
-8.174042764011080209e-02,
-1.302990975253251471e-02,
-3.358641333727325172e-03,
-8.254973880486437751e-03,
-1.124942519007465433e-02,
-6.652537774274364275e-03,
-1.238246082072965715e-01,
-1.489132543146572951e-01,
-7.089565803241293374e-02,
-1.464853208203966035e-02,
-1.351549645138465719e-02,
-4.928704993349256047e-02,
-8.335904996961795987e-02,
-6.077926847299328084e-02,
-3.212965324071682255e-02,
-4.661632308980576817e-02,
-2.670726843686788837e-02,
-7.931249414585008276e-03,
-2.217512591424788265e-02,
-1.052104514179644096e-01,
-2.193233256482181037e-01,
-1.966626130351180612e-01,
-3.609527794800932929e-03,
-6.304533973430329584e-03,
-4.378373401316826632e-03,
-2.282257484605074160e-03,
-1.602436106212073302e-02,
-9.549871744092154613e-02,
-2.387467936023038306e-01,
-2.508864610736074030e-01,
-1.756205227515252021e-04,
-3.698552022923825948e-04,
-3.204872212424146301e-04,
-7.834132074814580690e-04,
-1.254432305368037223e-02,
-8.659629462863223381e-02,
-2.274164372957538371e-01,
-2.322723042842752550e-01,
-3.698552022923826083e-06,
-9.468940627616796875e-06,
-1.934253683761037829e-05,
-5.762295493045434085e-04,
-1.197780523835287152e-02,
-9.145216161715367942e-02,
-2.541237057326217186e-01,
-2.589795727211431364e-01,
-3.374827557022396693e-08,
-1.238246082072965630e-07,
-3.876600479169611586e-06,
-2.427933494260716731e-04,
-5.689457488217613233e-03,
-4.839680765226362508e-02,
-1.497225654794108740e-01,
-1.675274111039894709e-01
]

In [17]:
np.shape(errorvalues)

(64L,)

In [19]:
a = np.eye(64)
d = np.diag_indices_from(a)
a[d] = errorvalues
print(a)

[[-0.14891325  0.          0.         ...,  0.          0.          0.        ]
 [ 0.         -0.12382461  0.         ...,  0.          0.          0.        ]
 [ 0.          0.         -0.04054649 ...,  0.          0.          0.        ]
 ..., 
 [ 0.          0.          0.         ..., -0.04839681  0.          0.        ]
 [ 0.          0.          0.         ...,  0.         -0.14972257  0.        ]
 [ 0.          0.          0.         ...,  0.          0.         -0.16752741]]


In [20]:
lambdaa=0.8*a
lambdaa

array([[-0.1191306 ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        , -0.09905969,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.03243719, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ..., -0.03871745,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.11977805,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.13402193]])

In [21]:
corr_mat=np.corrcoef(returns_arr,rowvar=True)
print(corr_mat.shape)

#covariance matrix 
cov_mat = np.cov(returns_arr)
#cov_mat.shape
 
    
Similarity=corr_mat-lambdaa
Similarity.shape
np.shape(Similarity)
type(Similarity)

(64L, 64L)


numpy.ndarray

In [22]:
#jacobi function
#Input:     input covariance matrix,   correlation coeffs, masked components
#Output:   covariance of rotated data,  correlation coefficients for rotated data,      part of Jacobi rotation; rotation angle
#indices of components that are rotated,      highest correlation,      correlation coefficient for pair
# Description: Picks the two components with highest correlation coefficient. Decorrelate the two components with PCA
# maskno = components which have been already masked by this algo
     
    
from numpy import linalg as LA
global R

count =0
 

def newJacobi(C,cc,maskno):
    if (np.any(C)):
        count= +1
        if (np.any(cc)):
            count+=1
            if (maskno):
                count+=1
                 
    
     
   # maskno=np.array([]) #creating an empty array for masked components
     
    tri=np.triu(cc) #extract the uppar triangular of covariance matrix
    a=0
    if (maskno==[]):
        a=maskno[0]
    else:
        a=0
    tri[a,:]=-1
    tri[:,a]=-1  
    ind = tri.argmax(0)
    no1=ind[0]
    no2=ind[1]
    compno = [no1,no2]
    maxcc=cc[no1][no2]
    cred=np.zeros((2,2))
    cred[0][0]=C[no1][no1]
    cred[0][1]=C[no1][no2]
    cred[1][0]=C[no2][no1]
    cred[1][1]=C[no2][no2]
    if (cred[0][1]==0): # this means that already we have found diagnoal matrix
        Cnew=C
        ccnew=cc
        R=np.identity(2)
        theta=0
        idx=np.array([1,2])
    else:
        c11=cred[0][0]
        c12=cred[0][1]
        c21=cred[1][0]
        c22=cred[1][1]
        R=np.zeros((2,2))
        theta = 1/2 *(mt.atan(2*c12/(c11-c22)))
        cs=mt.cos(theta)
        sn=mt.sin(theta)
        R[0][0] =  cs
        R[0][1] = (-1)*sn
        R[1][0] = sn 
        R[1][1] = cs
        M=C
        Rtrans=R.T
        M[no1][no1]=Rtrans[0][0]*C[no1][no1]
        M[no1][no2]=Rtrans[0][1]*C[no1][no2]
        M[no2][no1]=Rtrans[1][0]*C[no2][no1]
        M[no2][no2]=Rtrans[1][1]*C[no2][no2]
        Cnew=M
        Cnew[no1][no1]=M[no1][no1]*R[0][0]
        Cnew[no1][no2]=M[no1][no2]*R[0][1]
        Cnew[no2][no1]=M[no2][no1]*R[1][0]
        Cnew[no2][no2]=M[no2][no2]*R[1][1]
        if (c11<c22):
            idx=np.array([2,1])
        else:
            idx=np.array([1,2])
        
        dnew=np.diag(Cnew)
        dnewT=dnew.T
        temp1=dnew[no1]*dnewT[no1]
        temp2=dnew[no2]*dnewT[no1]
        temp=temp1+temp2
        temp=mt.sqrt(temp)
        ccnew=cc
        ccnew[no1][:]=Cnew[no1][:]/temp
        ccnew[no2][:]=Cnew[no2][:]/temp #ccnew is 64 by 64  
        
    
   
    return  Cnew,ccnew,R,theta,compno,maxcc,idx

In [23]:
 # Build a hierical clustering tree
# inputs: covariance matrix, correlation coeffs,   maxlevel  
# outputs: positions of the two clusters merged, Element T{k} in the cell array contains a 2-by-2 rot matrix , ID of prinicipal 
# components,   all_nodes,   node labels,   theta ,    rotation angles that decorrelates inputs,   PC_ratio
#ratio C_qq/C_pp , hierarchical cluster tree,  labels of the d-components in the comp,updaated covariance matrix,correlation  


import sys
global count1 
count1=0
dim=64 #no od rows od covarince matrix
dim2=64 #no. of columns od covaraince matrix

def Build_JTree(C,cc,maxlevel):
    
           
     
    if (np.any(C)):
        count1= +1
        if (np.any(cc)):
            count1+=1
            if (maxlevel):
                count1+=1
                 
                       
  
            
     
             
    J=maxlevel-1    
    Z = np.zeros((J,3))   # columns 1 and 2 contain the indices of the nodes that are merged
    T = np.ones((2,2))  # 2-by-2 rotation matrices for levels L=0,1,..,J-1
    theta = np.zeros((J,1)) #rotation angles
    PCidx=np.zeros((J,2))  # order of principal components, [1 2] or [2 1]
        
    L=0
    maskno=np.array([]) #0L
    nodes=np.zeros((1,64)) #1L by 64L
    dlabels=np.zeros((1,dim)) #1L by 64L
    PC_ratio=np.zeros((dim-1,1)) #63L by 1L
    Zpos=np.zeros((J,2)) #19L by 2L
    all_d=np.zeros((J,dim)) #19L by 64L
    all_nodes=np.zeros((J,dim)) #19L by 64L
    
    
    for lev in range (J-1):
        [Cnew,ccnew,R,th,compno,maxcc,idx]=newJacobi(C,cc,maskno)
        dist = (1-maxcc)/2
        no1=compno[0]
        no2=compno[1]
        Zpos[:][lev]=dist
        Zpos[no1][:]=nodes[0][no1]
        Zpos[no2][:]=nodes[0][no2]
        T=R
        theta[lev]=th
        PCidx[lev][:]=idx
        C=Cnew
        cc=ccnew
        component1=idx[0]
        component2=idx[1]
        pind=[component1,component2]
        p1=pind[0]
        p2=pind[1]
        nodes[0][p1]=np.array([dim+lev])
        nodes[0][p2]=np.array([dim+lev])
        dlabels[0][p2]=np.array((lev)) #abels of d-components in vector
        maskno=[maskno,p2]
        PC_ratio[lev]=C[p2][p2]/C[p1][p1]
        Zpos[lev][:] =np.array(compno) # their positions in the component vector
        transdlabels=dlabels.T
        all_d[lev][:]=transdlabels[0]
        all_nodes[lev][:]=nodes 
        
    return  Zpos,T,PCidx,maxlevel,all_nodes,Cnew,nodes

In [24]:
maxlevel=5
[Zpos,T,PCidx,maxlev,all_nodes,Cnew,nodes]=Build_JTree(cov_mat,Similarity,maxlevel)
all_nodes

np.shape(all_nodes)
type(Zpos)
np.shape(Zpos)
Zpos

array([[  0.,   0.],
       [ 65.,  65.],
       [  0.,   1.],
       [  0.,   0.]])

In [25]:
#Calculate the basis for the Jacobi tree algorithm
#inputs : hierarchical cluster information, Element T{k} in the cell array contains a 2-by-2 matrix, id of principal components  
# maxlev, node labels
#outputs : Output:   basis(m,m),    sums(J,m),  difs(J,m)  
 
global basis
def JTree_Basis(Zpos,T,PCidx,maxlev,all_nodes,nodes):
    J=np.shape(Zpos[1])
    m=np.shape(all_nodes[0])
    nodes=np.zeros((1,64))
    nodes = all_nodes[0][:]
    nodes= np.nonzero(nodes)
    del all_nodes
    tmpfilts=np.diag(np.ones(m))
    ind=np.zeros(J)
    sums=np.zeros((maxlev,64))
    difs=np.zeros((maxlev,64))
    for lev in range(4):
        d1=Zpos[lev,0:1]
        d1=int(d1)
        if d1<64:
            s=tmpfilts[d1,:]
        else:
            d2=d1-2
            s=tmpfilts[d2,:]
        R=T
        y=(R.T)*s[lev]
        if d1<64:
            tmpfilts[d1,lev]=y[0][1]
        else:
            d2=d1-2
            tmpfilts[d2,lev]=y[0][1]
        t1=PCidx[0][0]
        t2=PCidx[0][1]
        t1=int(t1)
        t2=int(t2)
        y=y[t1:t2,:]
        sums[lev,:]=y[0][0]
        difs[lev,:]=y[0][1]
        
    tmp = [np.diag(np.ones(m)), sums]
    p=np.flipud(difs)
    tt1=nodes[0][0]
           
    basis  = [tmp[tt1], p]
     
    
     
    
    return sums,difs,basis


In [26]:
maxlev=5
sums,difs,basis=JTree_Basis(Zpos,T,PCidx,maxlev,all_nodes,nodes)
np.shape(basis)
b2=basis[1][maxlev-1][:] #
b2

array([ 0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447])

In [27]:
import pandas as pd
import numpy as np
signal=DataFile.iloc[:,5:6]
sparsify= signal.to_sparse()
sparsify
signal.as_matrix()

array([[  1.84000000e-01],
       [  1.53000000e-01],
       [  5.01000000e-02],
       [  6.51000000e-03],
       [  5.59000000e-04],
       [  5.98000000e-04],
       [  6.57000000e-04],
       [  3.14000000e-04],
       [  2.55000000e-01],
       [  2.55000000e-01],
       [  1.01000000e-01],
       [  1.61000000e-02],
       [  4.15000000e-03],
       [  1.02000000e-02],
       [  1.39000000e-02],
       [  8.22000000e-03],
       [  1.53000000e-01],
       [  1.84000000e-01],
       [  8.76000000e-02],
       [  1.81000000e-02],
       [  1.67000000e-02],
       [  6.09000000e-02],
       [  1.03000000e-01],
       [  7.51000000e-02],
       [  3.97000000e-02],
       [  5.76000000e-02],
       [  3.30000000e-02],
       [  9.80000000e-03],
       [  2.74000000e-02],
       [  1.30000000e-01],
       [  2.71000000e-01],
       [  2.43000000e-01],
       [  4.46000000e-03],
       [  7.79000000e-03],
       [  5.41000000e-03],
       [  2.82000000e-03],
       [  1.98000000e-02],
 

In [28]:
MeanOfData=returns_arr.mean(1)
MeanData=MeanOfData.sum(axis=0)/64
MeanData
VarData=np.var(returns_arr,1)
VarData=VarData.sum(axis=0)/64
VarData
#phie matrix that is the measurement matrix
phie=0.004 * np.random.randn(64) + 0.003
np.shape(phie)

(64L,)

In [29]:
newx=phie.dot(b2.T)
y=np.multiply(newx,sparsify)
print(y)
print(np.shape(y))

             0.4
0   2.834869e-02
1   2.357255e-02
2   7.718856e-03
3   1.002989e-03
4   8.612456e-05
5   9.213325e-05
6   1.012233e-04
7   4.837766e-05
8   3.928759e-02
9   3.928759e-02
10  1.556097e-02
11  2.480510e-03
12  6.393862e-04
13  1.571504e-03
14  2.141559e-03
15  1.266447e-03
16  2.357255e-02
17  2.834869e-02
18  1.349644e-02
19  2.788648e-03
20  2.572952e-03
21  9.382801e-03
22  1.586910e-02
23  1.157058e-02
24  6.116538e-03
25  8.874373e-03
26  5.084276e-03
27  1.509876e-03
28  4.221490e-03
29  2.002897e-02
..           ...
34  8.335132e-04
35  4.344745e-04
36  3.050566e-03
37  1.818014e-02
38  4.545035e-02
39  4.776138e-02
40  3.343297e-05
41  7.040952e-05
42  6.101131e-05
43  1.491388e-04
44  2.388069e-03
45  1.648538e-02
46  4.329338e-02
47  4.421780e-02
48  7.040952e-07
49  1.802607e-06
50  3.682248e-06
51  1.096971e-04
52  2.280221e-03
53  1.740979e-02
54  4.837766e-02
55  4.930207e-02
56  6.424676e-09
57  2.357255e-08
58  7.379904e-07
59  4.622069e-05
60  1.083105e-

In [30]:
y1=y.to_dense()
y1

0.4
0   2.834869e-02
1   2.357255e-02
2   7.718856e-03
3   1.002989e-03
4   8.612456e-05
5   9.213325e-05
6   1.012233e-04
7   4.837766e-05
8   3.928759e-02
9   3.928759e-02
10  1.556097e-02
11  2.480510e-03
12  6.393862e-04
13  1.571504e-03
14  2.141559e-03
15  1.266447e-03
16  2.357255e-02
17  2.834869e-02
18  1.349644e-02
19  2.788648e-03
20  2.572952e-03
21  9.382801e-03
22  1.586910e-02
23  1.157058e-02
24  6.116538e-03
25  8.874373e-03
26  5.084276e-03
27  1.509876e-03
28  4.221490e-03
29  2.002897e-02
..           ...
34  8.335132e-04
35  4.344745e-04
36  3.050566e-03
37  1.818014e-02
38  4.545035e-02
39  4.776138e-02
40  3.343297e-05
41  7.040952e-05
42  6.101131e-05
43  1.491388e-04
44  2.388069e-03
45  1.648538e-02
46  4.329338e-02
47  4.421780e-02
48  7.040952e-07
49  1.802607e-06
50  3.682248e-06
51  1.096971e-04
52  2.280221e-03
53  1.740979e-02
54  4.837766e-02
55  4.930207e-02
56  6.424676e-09
57  2.357255e-08
58  7.379904e-07
59  4.622069e-05
60  1.083105e-03
61  9.213325e-03
62  2.850276e-02
63  3.189228e-02

[64 rows x 1 columns]

In [31]:
np.mean(y-sparsify)#/np.mean(sparsify)

0.4   -0.069349
dtype: float64

In [32]:
LA.norm(y-sparsify)/LA.norm(sparsify)

0.84593102578938073