In [93]:
#importing necssary files
from __future__ import division, print_function, unicode_literals
import numpy as np
import pandas as pd 
get_ipython().magic(u'matplotlib inline')
import matplotlib
import math as mt
import matplotlib.pyplot as plt
from matplotlib.mlab import PCA

#printing versions of current packages in use 
print(np.__version__)
print(pd.__version__)
print(matplotlib.__version__)

#importing the csv file containing data of sensors, sorting them and selecting the required columns
DataFile = pd.read_csv('C:/Users/muneeba/Desktop/THESIS/DataDistributionPCA.csv')
location=DataFile.iloc[:,1:3]
DataSensors=DataFile.iloc[:,4:68]



#converting the sliced data into matrices 
returns = DataSensors[[key for key in dict(DataSensors.dtypes) if dict(DataSensors.dtypes)[key] in ['float64', 'int64']]] 
returns = returns[:65]
returns_arr = returns.as_matrix()[:65]
locations = location[[key for key in dict(location.dtypes) if dict(location.dtypes)[key] in ['float64', 'int64']]] 
locations = locations[:65] 
locations_arr = locations.as_matrix()[:65]

1.12.1
0.22.0
2.2.0


In [94]:
locations_arr

array([[ 1,  1],
       [ 3,  1],
       [ 5,  1],
       [ 7,  1],
       [ 9,  1],
       [11,  1],
       [13,  1],
       [15,  1],
       [ 1,  3],
       [ 3,  3],
       [ 5,  3],
       [ 7,  3],
       [ 9,  3],
       [11,  3],
       [13,  3],
       [15,  3],
       [ 1,  5],
       [ 3,  5],
       [ 5,  5],
       [ 7,  5],
       [ 9,  5],
       [11,  5],
       [13,  5],
       [15,  5],
       [ 1,  7],
       [ 3,  7],
       [ 5,  7],
       [ 7,  7],
       [ 9,  7],
       [11,  7],
       [13,  7],
       [15,  7],
       [ 1,  9],
       [ 3,  9],
       [ 5,  9],
       [ 7,  9],
       [ 9,  9],
       [11,  9],
       [13,  9],
       [15,  9],
       [ 1, 11],
       [ 3, 11],
       [ 5, 11],
       [ 7, 11],
       [ 9, 11],
       [11, 11],
       [13, 11],
       [15, 11],
       [ 1, 13],
       [ 3, 13],
       [ 5, 13],
       [ 7, 13],
       [ 9, 13],
       [11, 13],
       [13, 13],
       [15, 13],
       [ 1, 15],
       [ 3, 15],
       [ 5, 15

In [95]:
from scipy.spatial import distance
distsensors=distance.cdist(locations_arr, locations_arr, 'euclidean')
np.shape(distsensors)

(64L, 64L)

In [96]:
distsensors

array([[  0.        ,   2.        ,   4.        , ...,  17.20465053,
         18.43908891,  19.79898987],
       [  2.        ,   0.        ,   2.        , ...,  16.1245155 ,
         17.20465053,  18.43908891],
       [  4.        ,   2.        ,   0.        , ...,  15.23154621,
         16.1245155 ,  17.20465053],
       ..., 
       [ 17.20465053,  16.1245155 ,  15.23154621, ...,   0.        ,
          2.        ,   4.        ],
       [ 18.43908891,  17.20465053,  16.1245155 , ...,   2.        ,
          0.        ,   2.        ],
       [ 19.79898987,  18.43908891,  17.20465053, ...,   4.        ,
          2.        ,   0.        ]])

In [97]:
maxdis=np.max(distsensors)
maxdis   # maximum distance will be between last and first sensor

19.798989873223331

In [98]:
#dviding by the maximum value throughout
NormDist=np.divide(distsensors,maxdis)
NormDist

array([[ 0.        ,  0.10101525,  0.20203051, ...,  0.86896608,
         0.93131463,  1.        ],
       [ 0.10101525,  0.        ,  0.10101525, ...,  0.81441102,
         0.86896608,  0.93131463],
       [ 0.20203051,  0.10101525,  0.        , ...,  0.76930926,
         0.81441102,  0.86896608],
       ..., 
       [ 0.86896608,  0.81441102,  0.76930926, ...,  0.        ,
         0.10101525,  0.20203051],
       [ 0.93131463,  0.86896608,  0.81441102, ...,  0.10101525,
         0.        ,  0.10101525],
       [ 1.        ,  0.93131463,  0.86896608, ...,  0.20203051,
         0.10101525,  0.        ]])

In [99]:
#normalized
maxdisNorm=np.max(NormDist)
maxdisNorm

1.0

In [100]:
#multiplying by lambda to scale the parameter for geographical location
#let lambda is 0.5 
DistParameter=np.multiply(0.5,NormDist)
DistParameter

array([[ 0.        ,  0.05050763,  0.10101525, ...,  0.43448304,
         0.46565731,  0.5       ],
       [ 0.05050763,  0.        ,  0.05050763, ...,  0.40720551,
         0.43448304,  0.46565731],
       [ 0.10101525,  0.05050763,  0.        , ...,  0.38465463,
         0.40720551,  0.43448304],
       ..., 
       [ 0.43448304,  0.40720551,  0.38465463, ...,  0.        ,
         0.05050763,  0.10101525],
       [ 0.46565731,  0.43448304,  0.40720551, ...,  0.05050763,
         0.        ,  0.05050763],
       [ 0.5       ,  0.46565731,  0.43448304, ...,  0.10101525,
         0.05050763,  0.        ]])

In [108]:
#now adding the data part for ths algorithum
corr_mat=np.corrcoef(returns_arr,rowvar=True)
print(corr_mat.shape)

#covariance matrix 
cov_mat = np.cov(returns_arr)
#cov_mat.shape
 
    
Similarity=np.subtract(corr_mat,DistParameter)
Similarity.shape
np.shape(Similarity)
type(Similarity)
 

(64L, 64L)


numpy.ndarray

In [102]:
  #jacobi function
#Input:     input covariance matrix,   correlation coeffs, masked components
#Output:   covariance of rotated data,  correlation coefficients for rotated data,      part of Jacobi rotation; rotation angle
#indices of components that are rotated,      highest correlation,      correlation coefficient for pair
# Description: Picks the two components with highest correlation coefficient. Decorrelate the two components with PCA
# maskno = components which have been already masked by this algo
     
    
from numpy import linalg as LA
global R

count =0
 

def newJacobi(C,cc,maskno):
    if (np.any(C)):
        count= +1
        if (np.any(cc)):
            count+=1
            if (maskno):
                count+=1
                 
    
     
   # maskno=np.array([]) #creating an empty array for masked components
     
    tri=np.triu(cc) #extract the uppar triangular of covariance matrix
    a=0
    if (maskno==[]):
        a=maskno[0]
    else:
        a=0
    tri[a,:]=-1
    tri[:,a]=-1  
    ind = tri.argmax(0)
    no1=ind[0]
    no2=ind[1]
    compno = [no1,no2]
    maxcc=cc[no1][no2]
    cred=np.zeros((2,2))
    cred[0][0]=C[no1][no1]
    cred[0][1]=C[no1][no2]
    cred[1][0]=C[no2][no1]
    cred[1][1]=C[no2][no2]
    if (cred[0][1]==0): # this means that already we have found diagnoal matrix
        Cnew=C
        ccnew=cc
        R=np.identity(2)
        theta=0
        idx=np.array([1,2])
    else:
        c11=cred[0][0]
        c12=cred[0][1]
        c21=cred[1][0]
        c22=cred[1][1]
        R=np.zeros((2,2))
        theta = 1/2 *(mt.atan(2*c12/(c11-c22)))
        cs=mt.cos(theta)
        sn=mt.sin(theta)
        R[0][0] =  cs
        R[0][1] = (-1)*sn
        R[1][0] = sn 
        R[1][1] = cs
        M=C
        Rtrans=R.T
        M[no1][no1]=Rtrans[0][0]*C[no1][no1]
        M[no1][no2]=Rtrans[0][1]*C[no1][no2]
        M[no2][no1]=Rtrans[1][0]*C[no2][no1]
        M[no2][no2]=Rtrans[1][1]*C[no2][no2]
        Cnew=M
        Cnew[no1][no1]=M[no1][no1]*R[0][0]
        Cnew[no1][no2]=M[no1][no2]*R[0][1]
        Cnew[no2][no1]=M[no2][no1]*R[1][0]
        Cnew[no2][no2]=M[no2][no2]*R[1][1]
        if (c11<c22):
            idx=np.array([2,1])
        else:
            idx=np.array([1,2])
        
        dnew=np.diag(Cnew)
        dnewT=dnew.T
        temp1=dnew[no1]*dnewT[no1]
        temp2=dnew[no2]*dnewT[no1]
        temp=temp1+temp2
        temp=mt.sqrt(temp)
        ccnew=cc
        ccnew[no1][:]=Cnew[no1][:]/temp
        ccnew[no2][:]=Cnew[no2][:]/temp #ccnew is 64 by 64  
        
    
   
    return  Cnew,ccnew,R,theta,compno,maxcc,idx

In [103]:
 # Build a hierical clustering tree
# inputs: covariance matrix, correlation coeffs,   maxlevel  
# outputs: positions of the two clusters merged, Element T{k} in the cell array contains a 2-by-2 rot matrix , ID of prinicipal 
# components,   all_nodes,   node labels,   theta ,    rotation angles that decorrelates inputs,   PC_ratio
#ratio C_qq/C_pp , hierarchical cluster tree,  labels of the d-components in the comp,updaated covariance matrix,correlation  


import sys
global count1 
count1=0
dim=64 #no od rows od covarince matrix
dim2=64 #no. of columns od covaraince matrix

def Build_JTree(C,cc,maxlevel):
    
           
     
    if (np.any(C)):
        count1= +1
        if (np.any(cc)):
            count1+=1
            if (maxlevel):
                count1+=1
                 
                       
  
            
     
             
    J=maxlevel-1    
    Z = np.zeros((J,3))   # columns 1 and 2 contain the indices of the nodes that are merged
    T = np.ones((2,2))  # 2-by-2 rotation matrices for levels L=0,1,..,J-1
    theta = np.zeros((J,1)) #rotation angles
    PCidx=np.zeros((J,2))  # order of principal components, [1 2] or [2 1]
        
    L=0
    maskno=np.array([]) #0L
    nodes=np.zeros((1,64)) #1L by 64L
    dlabels=np.zeros((1,dim)) #1L by 64L
    PC_ratio=np.zeros((dim-1,1)) #63L by 1L
    Zpos=np.zeros((J,2)) #19L by 2L
    all_d=np.zeros((J,dim)) #19L by 64L
    all_nodes=np.zeros((J,dim)) #19L by 64L
    
    
    for lev in range (J-1):
        [Cnew,ccnew,R,th,compno,maxcc,idx]=newJacobi(C,cc,maskno)
        dist = (1-maxcc)/2
        no1=compno[0]
        no2=compno[1]
        Zpos[:][lev]=dist
        Zpos[no1][:]=nodes[0][no1]
        Zpos[no2][:]=nodes[0][no2]
        T=R
        theta[lev]=th
        PCidx[lev][:]=idx
        C=Cnew
        cc=ccnew
        component1=idx[0]
        component2=idx[1]
        pind=[component1,component2]
        p1=pind[0]
        p2=pind[1]
        nodes[0][p1]=np.array([dim+lev])
        nodes[0][p2]=np.array([dim+lev])
        dlabels[0][p2]=np.array((lev)) #abels of d-components in vector
        maskno=[maskno,p2]
        PC_ratio[lev]=C[p2][p2]/C[p1][p1]
        Zpos[lev][:] =np.array(compno) # their positions in the component vector
        transdlabels=dlabels.T
        all_d[lev][:]=transdlabels[0]
        all_nodes[lev][:]=nodes 
        
    return  Zpos,T,PCidx,maxlevel,all_nodes,Cnew,nodes

In [104]:
 maxlevel=5
[Zpos,T,PCidx,maxlev,all_nodes,Cnew,nodes]=Build_JTree(cov_mat,Similarity,maxlevel)
all_nodes

np.shape(all_nodes)
type(Zpos)
np.shape(Zpos)
Zpos
    

array([[  0.,   0.],
       [ 65.,  65.],
       [  0.,   1.],
       [  0.,   0.]])

In [105]:
 #Calculate the basis for the Jacobi tree algorithm
#inputs : hierarchical cluster information, Element T{k} in the cell array contains a 2-by-2 matrix, id of principal components  
# maxlev, node labels
#outputs : Output:   basis(m,m),    sums(J,m),  difs(J,m)  
 
global basis
def JTree_Basis(Zpos,T,PCidx,maxlev,all_nodes,nodes):
    J=np.shape(Zpos[1])
    m=np.shape(all_nodes[0])
    nodes=np.zeros((1,64))
    nodes = all_nodes[0][:]
    nodes= np.nonzero(nodes)
    del all_nodes
    tmpfilts=np.diag(np.ones(m))
    ind=np.zeros(J)
    sums=np.zeros((maxlev,64))
    difs=np.zeros((maxlev,64))
    for lev in range(4):
        d1=Zpos[lev,0:1]
        d1=int(d1)
        if d1<64:
            s=tmpfilts[d1,:]
        else:
            d2=d1-2
            s=tmpfilts[d2,:]
        R=T
        y=(R.T)*s[lev]
        if d1<64:
            tmpfilts[d1,lev]=y[0][1]
        else:
            d2=d1-2
            tmpfilts[d2,lev]=y[0][1]
        t1=PCidx[0][0]
        t2=PCidx[0][1]
        t1=int(t1)
        t2=int(t2)
        y=y[t1:t2,:]
        sums[lev,:]=y[0][0]
        difs[lev,:]=y[0][1]
        
    tmp = [np.diag(np.ones(m)), sums]
    p=np.flipud(difs)
    tt1=nodes[0][0]
           
    basis  = [tmp[tt1], p]
     
    
     
    
    return sums,difs,basis


In [106]:
maxlev=5
sums,difs,basis=JTree_Basis(Zpos,T,PCidx,maxlev,all_nodes,nodes)
np.shape(basis)
b2=basis[1][maxlev-1][:] #
b2

array([ 0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447,  0.84304447,
        0.84304447,  0.84304447,  0.84304447,  0.84304447])

In [107]:
import pandas as pd
import numpy as np
signal=DataFile.iloc[:,5:6]
sparsify= signal.to_sparse()
sparsify
signal.as_matrix()

array([[  1.84000000e-01],
       [  1.53000000e-01],
       [  5.01000000e-02],
       [  6.51000000e-03],
       [  5.59000000e-04],
       [  5.98000000e-04],
       [  6.57000000e-04],
       [  3.14000000e-04],
       [  2.55000000e-01],
       [  2.55000000e-01],
       [  1.01000000e-01],
       [  1.61000000e-02],
       [  4.15000000e-03],
       [  1.02000000e-02],
       [  1.39000000e-02],
       [  8.22000000e-03],
       [  1.53000000e-01],
       [  1.84000000e-01],
       [  8.76000000e-02],
       [  1.81000000e-02],
       [  1.67000000e-02],
       [  6.09000000e-02],
       [  1.03000000e-01],
       [  7.51000000e-02],
       [  3.97000000e-02],
       [  5.76000000e-02],
       [  3.30000000e-02],
       [  9.80000000e-03],
       [  2.74000000e-02],
       [  1.30000000e-01],
       [  2.71000000e-01],
       [  2.43000000e-01],
       [  4.46000000e-03],
       [  7.79000000e-03],
       [  5.41000000e-03],
       [  2.82000000e-03],
       [  1.98000000e-02],
 

In [88]:
MeanOfData=returns_arr.mean(1)
MeanData=MeanOfData.sum(axis=0)/64
MeanData
VarData=np.var(returns_arr,1)
VarData=VarData.sum(axis=0)/64
VarData
#phie matrix that is the measurement matrix
phie=0.004 * np.random.randn(64) + 0.003
np.shape(phie) 

(64L,)

In [89]:
newx=phie.dot(b2.T)
y=np.multiply(newx,sparsify)
print(y)
print(np.shape(y)) 

             0.4
0   2.653897e-02
1   2.206773e-02
2   7.226099e-03
3   9.389602e-04
4   8.062653e-05
5   8.625164e-05
6   9.476142e-05
7   4.528932e-05
8   3.677955e-02
9   3.677955e-02
10  1.456758e-02
11  2.322160e-03
12  5.985691e-04
13  1.471182e-03
14  2.004846e-03
15  1.185599e-03
16  2.206773e-02
17  2.653897e-02
18  1.263486e-02
19  2.610627e-03
20  2.408700e-03
21  8.783821e-03
22  1.485605e-02
23  1.083194e-02
24  5.726070e-03
25  8.307850e-03
26  4.759706e-03
27  1.413488e-03
28  3.951998e-03
29  1.875036e-02
..           ...
34  7.803033e-04
35  4.067385e-04
36  2.855824e-03
37  1.701955e-02
38  4.254889e-02
39  4.471239e-02
40  3.129867e-05
41  6.591472e-05
42  5.711647e-05
43  1.396180e-04
44  2.235619e-03
45  1.543299e-02
46  4.052962e-02
47  4.139502e-02
48  6.591472e-07
49  1.687532e-06
50  3.447181e-06
51  1.026943e-04
52  2.134656e-03
53  1.629839e-02
54  4.528932e-02
55  4.615472e-02
56  6.014537e-09
57  2.206773e-08
58  6.908785e-07
59  4.327005e-05
60  1.013962e-

In [90]:
y1=y.to_dense
y1

<bound method SparseDataFrame.to_dense of              0.4
0   2.653897e-02
1   2.206773e-02
2   7.226099e-03
3   9.389602e-04
4   8.062653e-05
5   8.625164e-05
6   9.476142e-05
7   4.528932e-05
8   3.677955e-02
9   3.677955e-02
10  1.456758e-02
11  2.322160e-03
12  5.985691e-04
13  1.471182e-03
14  2.004846e-03
15  1.185599e-03
16  2.206773e-02
17  2.653897e-02
18  1.263486e-02
19  2.610627e-03
20  2.408700e-03
21  8.783821e-03
22  1.485605e-02
23  1.083194e-02
24  5.726070e-03
25  8.307850e-03
26  4.759706e-03
27  1.413488e-03
28  3.951998e-03
29  1.875036e-02
..           ...
34  7.803033e-04
35  4.067385e-04
36  2.855824e-03
37  1.701955e-02
38  4.254889e-02
39  4.471239e-02
40  3.129867e-05
41  6.591472e-05
42  5.711647e-05
43  1.396180e-04
44  2.235619e-03
45  1.543299e-02
46  4.052962e-02
47  4.139502e-02
48  6.591472e-07
49  1.687532e-06
50  3.447181e-06
51  1.026943e-04
52  2.134656e-03
53  1.629839e-02
54  4.528932e-02
55  4.615472e-02
56  6.014537e-09
57  2.206773e-08
58  6.

In [91]:
 np.mean(y-sparsify)#/np.mean(sparsify) 

0.4   -0.070156
dtype: float64

In [92]:
LA.norm(y-sparsify)/LA.norm(sparsify)

0.85576648704334146